// Generated by CoffeeScript 1.4.0
(function() {

  Footnotes.Views.FocalNoteView = Backbone.View.extend({
    tagName: 'div',
    className: 'footnote',
    initialize: function() {
      this.$el.addClass("" + (this.model.get("noteType")));
      return this.$el.attr('id', "" + (this.model.get("noteType")) + (this.model.get("id")));
    },
    render: function() {
      this.$el.html(Footnotes.template('notes/staticQuestionTemplate').render(this.context()));
      return this;
    },
    context: function() {
      return {
        title: this.model.get("title"),
        creatorName: this.model.get("creatorName"),
        canEdit: Footnotes.currentUser.get('username') === this.model.get('creatorName'),
        content: this.model.get("content"),
        id: this.model.get("id"),
        createdAt: this.model.get("createdAt"),
        creatorID: this.model.get("creatorID"),
        createdAtPretty: this.model.get("createdAtPretty"),
        noteType: this.model.get("noteType")
      };
    }
  });

}).call(this);
