// Generated by CoffeeScript 1.4.0
(function() {

  Footnotes.Views.NewQuestionFormView = Backbone.View.extend({
    events: {
      'submit form': 'submit',
      'click .open': 'openForm',
      'click .close': 'onClose'
    },
    initialize: function(options) {
      return this.questions = options.questions;
    },
    render: function() {
      this.closeForm();
      return this;
    },
    onClose: function(event) {
      event.preventDefault();
      return this.closeForm();
    },
    closeForm: function() {
      var contents;
      contents = Footnotes.template('newQuestion').render();
      return this.$el.html(contents);
    },
    openForm: function() {
      var content;
      content = Footnotes.template('forms/questionFormTemplate').render();
      return this.$el.html(content);
    },
    submit: function(event) {
      var data;
      event.preventDefault();
      data = Footnotes.formToObj(this.$('form'));
      data['external_url'] = Footnotes.Overlay.getExternalURL();
      data['createdAt'] = (new Date).toISOString();
      this.questions.create(data);
      return this.closeForm();
    }
  });

}).call(this);
