// Generated by CoffeeScript 1.4.0
(function() {

  Footnotes.Views.NoteListView = Backbone.View.extend({
    el: '.notes',
    initialize: function() {
      this.collection.on('add', this.renderQuestions, this);
      return this.collection.on('reset', this.renderQuestions, this);
    },
    render: function() {
      this.renderQuestions();
      return this;
    },
    renderQuestions: function() {
      var _this = this;
      this.$el.empty();
      return this.collection.each(function(question) {
        var view;
        view = new Footnotes.Views.QuestionView({
          model: question
        });
        return _this.$el.append(view.render().el);
      });
    }
  });

}).call(this);
