// Generated by CoffeeScript 1.4.0
(function() {

  Footnotes.Views.NoteFocusView = Backbone.View.extend({
    events: {
      'click .goUp': 'onGoUp',
      'click .focus': 'onGoUp',
      'click a': 'onLinkClick'
    },
    render: function() {
      this.$el.html(Footnotes.template('noteFocusTemplate').render());
      this.focus = new Footnotes.Views.FocalNoteView({
        model: this.model
      });
      this.form = new Footnotes.Views.ResponseFormView({
        parent: this.model
      });
      this.children = new Footnotes.Views.NoteListView({
        collection: this.model.get('children')
      });
      this.$el.find('.children').html(this.children.render().el);
      this.$el.find('.focus').html(this.focus.render().el);
      this.$el.find('.form').html(this.form.render().el);
      return this;
    },
    onGoUp: function() {
      return this.$el.trigger({
        type: 'viewFootnote',
        model: this.model.get('parent')
      });
    },
    onLinkClick: function(event) {
      return event.stopPropagation();
    }
  });

}).call(this);
