// Generated by CoffeeScript 1.4.0
(function() {

  Footnotes.Views.OverlayView = Backbone.View.extend({
    el: '#right_bar',
    events: {
      'viewFootnote': 'onViewFootnote'
    },
    initialize: function(options) {
      return this.questions = options.questions;
    },
    render: function() {
      this.$el.html(Footnotes.template('overlayTemplate').render());
      this.form = new Footnotes.Views.NewQuestionFormView({
        questions: this.questions
      });
      this.list = new Footnotes.Views.NoteListView({
        collection: this.questions
      });
      this.$el.find('.new').html(this.form.render().el);
      this.$el.append(this.list.render());
      return this;
    },
    onViewAll: function() {
      return this.render();
    },
    onViewFootnote: function(event) {
      var model;
      model = event.model;
      if (model) {
        this.view = new Footnotes.Views.NoteFocusView({
          model: event.model,
          parentList: event.parentList
        });
        return this.$el.html(this.view.render().el);
      } else {
        return this.render();
      }
    }
  });

}).call(this);
