// Generated by CoffeeScript 1.4.0
(function() {

  Footnotes.Views.ResponseFormView = Backbone.View.extend({
    events: {
      'submit form': 'submit',
      'click .open': 'openForm',
      'click .close': 'onClose'
    },
    initialize: function(options) {
      return this.parent = options.parent;
    },
    render: function() {
      this.closeForm();
      return this;
    },
    onClose: function(event) {
      event.preventDefault();
      return this.closeForm();
    },
    closeForm: function() {
      var contents;
      contents = $('<button>').addClass('open').text('reply');
      return this.$el.html(contents);
    },
    openForm: function() {
      var content, context;
      context = {
        title: "Re: " + (this.parent.get('title'))
      };
      content = Footnotes.template('forms/questionFormTemplate').render(context);
      return this.$el.html(content);
    },
    submit: function(event) {
      var data;
      event.preventDefault();
      data = Footnotes.formToObj(this.$('form'));
      data['external_url'] = Footnotes.Overlay.getExternalURL();
      data['createdAt'] = (new Date).toISOString();
      data['parentID'] = this.parent.get('id');
      this.parent.get('children').create(data);
      return this.closeForm();
    }
  });

}).call(this);
