// Generated by CoffeeScript 1.4.0
(function() {

  Footnotes.template = function(templateName) {
    return Footnotes.mustacheWrapper().create(templateName);
  };

  Footnotes.mustacheWrapper = function() {
    return {
      create: function(templateName) {
        var name;
        name = templateName.match(/[^\/]+$/)[0];
        this.currentTemplate = Footnotes.templates[name];
        return this;
      },
      render: function(context) {
        return Mustache.render(this.currentTemplate, context);
      }
    };
  };

  Footnotes.templates = {
    questionFormTemplate: "<form>\n  <input size=28 type=\"text\" name='title' value=\"{{title}}\"\n  class=\".boxsizingBorder\" placeholder=\"Title\"/>\n  <textarea rows=5 columns=40 name=\"content\" \n  class=\"resize_vertical .boxsizingBorder\"\n  placeholder=\"Question\">{{content}}</textarea>\n  <br/>\n  {{#id}}\n  <input type=\"hidden\" name=\"id\" value=\"{{id}}\" />\n  {{/id}}\n  <input type=\"submit\" value={{^id}}\"ask\"{{/id}}{{#id}}\"save\"{{/id}} />\n  <button class=\"close\">cancel</button>\n  {{#id}}\n  <button class=\"delete\">delete</button>\n  {{/id}}\n</form>",
    questionTemplate: "<div class=\"title\">\n  <span class=\"minimize clickable\">-</span>\n  <span class=\"text\">{{title}}</span>\n</div>\n\n<div class=\"info\">\n  <span class=\"author\">\n    {{#creatorID}}\n      <a class=\"toCreatorPage\" href=\"/users/{{creatorID}}\">{{creatorName}}</a>\n    {{/creatorID}} \n    {{^creatorID}}\n    anonymous\n    {{/creatorID}}\n    at {{createdAtPretty}}\n  </span>\n</div>\n\n<div class=\"content\">\n <span class=\"type_indicator\">Q</span> {{content}} <br/>\n <span class=\"responses\">{{descendantCount}} below</span>\n</div>\n<div class=\"pusher\"></div>\n{{#canEdit}}\n<button class=\"edit\">edit</button>\n{{/canEdit}}",
    staticQuestionTemplate: "<div class=\"title\">\n  <span class=\"text\">{{title}}</span>\n</div>\n\n<div class=\"info\">\n  <span class=\"author\">\n    {{#creatorID}}\n      <a class=\"toCreatorPage\" href=\"/users/{{creatorID}}\">{{creatorName}}</a>\n    {{/creatorID}} \n    {{^creatorID}}\n    anonymous\n    {{/creatorID}}\n    at {{createdAtPretty}}\n  </span>\n</div>\n\n<div class=\"content\">\n  <span class=\"type_indicator\">Q</span> {{content}}\n  <span class=\"responses\">{{descendantCount}} responses</span>\n  <div class=\"pusher\"></div>\n</div>",
    noteFocusTemplate: "<button class=\"goUp\">back</button>\n<div class=\"focus\"></div>\n<hr/>\n<div class=\"form\"></div>\n<div class=\"children\"></div>",
    overlayTemplate: "<h1>\n  Q &amp; A\n</h1>\n<div class=\"new\"></div>\n<div class=\"notes\"></div>"
  };

}).call(this);
