// Generated by CoffeeScript 1.4.0
(function() {

  Footnotes.Collections.Questions = Backbone.Collection.extend({
    model: Footnotes.Models.Question,
    url: function() {
      return '/question_notes' + location.search;
    },
    initialize: function(models, options) {
      if (options) {
        this.parent = options[0].parent;
      }
      this.on('add', this.onAdd, this);
      return this.on('reset', this.onReset, this);
    },
    onAdd: function() {
      return this.setParent();
    },
    onReset: function() {
      return this.setParent();
    },
    setParent: function() {
      var _this = this;
      return this.each(function(model) {
        return model.set('parent', _this.parent);
      });
    },
    comparator: function(questionA, questionB) {
      var a, b, value;
      a = questionA.get("createdAt");
      b = questionB.get("createdAt");
      if (a > b) {
        value = 1;
      }
      if (a < b) {
        value = -1;
      }
      if (a === b) {
        value = 0;
      }
      return -value;
    }
  });

}).call(this);
